"""Create digests table

Revision ID: 73aa8aa5c8e8
Revises: ec141a5adc31
Create Date: 2025-01-07 09:25:59.417578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73aa8aa5c8e8'
down_revision: Union[str, None] = 'ec141a5adc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
