"""Add video_url and audio_url to Digest

Revision ID: 003336b8d50d
Revises: 2d3a2f907e7d
Create Date: 2025-01-09 08:42:25.271208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003336b8d50d'
down_revision: Union[str, None] = '2d3a2f907e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('digests', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    ''' op.drop_column('digests', 'video_url')
    # op.drop_column('digests', 'audio_url')
    # ### end Alembic commands ### '''